A typical organisation loses 5% of its revenue to fraud each year. It is estimated that fraud is costing the UK economy 73 billion british pounds each year.
Credit card is the most famous example.Detecting fraud is typically challenging because of these 4 characteristics :
1. Fraud causes are in a minority, sometimes only 0.001% of a companies' transactions.
2. Fraudsters will also try their best to 'blend' in and conceal their activities
3. Moreover Fraudsters change their behaviour over time , so they find new methods to avoid getting caught
4. Lastly Fraudsters tend to work together and organize their activities in a network.

Credit card companies to deal with fraud  create ruled-based systems based on location and block transactions from risky zip codes.They might also create rules to block transactions from cards used too frequently for example 'in the last 30 minutes'. Some of these rules can be highly efficient and catch a fraud, while others cannot and results in false alarm too often.

Limitations of rule-based systems:
1. Fixed threshold per rule to determine fraud
2. Limited to yes/no outcomes
3. Fail to capture interactions between features

Machine learning models  doesn't have these limitations:
1. Machine learning models adapt to data , thus they change over time
2. Uses all the data combined rather than a threshold per feature
3. Can give a score rather than a yes/no answer
4. Will typically have a better performance and can be combined with rules

In [48]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns 
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['creditcard_sampledata_2.csv']


In [49]:

df=pd.read_csv('../input/creditcard_sampledata_2.csv',index_col=0)
df.index.name='Transaction_id'
df.head()


V1        V2        V3  ...         V28  Amount  Class
Transaction_id                                ...                           
221547         -1.191668  0.428409  1.640028  ...   -0.017444   27.44      0
184524          1.966614 -0.450087 -1.228586  ...   -0.071314   35.95      0
91201           1.528452 -1.296191 -0.890677  ...    0.025853   28.40      0
26115          -0.774614  1.100916  0.679080  ...    0.123856   43.20      0
201292         -1.075860  1.361160  1.496972  ...    0.029714   10.59      0

[5 rows x 30 columns]

In [ ]:
df.shape

In [ ]:
df.info()


In [ ]:
df.Amount.max()

In [ ]:
df.Amount.min()

In [ ]:
df.Amount.mean()

In [ ]:
fraud=pd.DataFrame(df[df['Class']==1])
fraud.index.name='Transaction_id'
fraud.head()

In [ ]:
x=fraud['Class'].value_counts()
x.head()
#uparxoun 300 sunallages pou einai fraud

In [ ]:
fraud.Amount.mean()
#i mesi Apati einai 120.44$ enw mia mesi kanoniki sunalagi einai 90$



In [ ]:
graph=sns.countplot(x='Amount',data=fraud)
graph.set( xticks=list( range(0,151,25) ), xticklabels=list( range(0,151,25) ) )
plt.xlim(0,150)
plt.ylim(0,60)
plt.show()

In [ ]:
graph2=sns.countplot(x='Amount',data=fraud)
graph2.set( xticks=list( range(0,26,2) ), xticklabels=list( range(0,26,2) ) )
plt.xlim(0,25)
plt.ylim(0,100)
plt.show()

In [ ]:
occ=df['Class'].value_counts()
print(occ)
print(occ/len(df.index))

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import svm

In [53]:
 X_train ,y_train =df.drop('Class',axis=1),df.Class
X_train, X_test, y_train, y_test = train_test_split(df.drop('Class', axis=1), df.Class, test_size=0.3)


Transaction_id
221547    0
184524    0
91201     0
26115     0
201292    0
70090     0
269172    0
13210     0
178722    0
207262    0
262113    0
77543     0
220598    0
232336    0
278850    0
58625     0
69927     0
107641    0
143884    0
211441    0
193443    0
210008    0
53979     0
196801    0
145720    0
273377    0
152450    0
180500    0
115000    0
54055     0
         ..
140786    1
274475    1
6329      1
276864    1
15781     1
50211     1
107637    1
152019    1
29687     1
237107    1
30496     1
42696     1
204064    1
64329     1
195383    1
64460     1
17317     1
59539     1
102445    1
143335    1
245347    1
11880     1
76929     1
189701    1
149869    1
96789     1
18809     1
197586    1
184379    1
145800    1
Name: Class, Length: 7300, dtype: int64

In [59]:
model=RandomForestClassifier(n_estimators=100, random_state=5)
model.fit(X_train,y_train)
predicted=model.predict(X_test)
probs=model.predict_proba(X_test)
print(roc_auc_score(y_test,probs[:,1]))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))


0.9599726405281961
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2106
           1       0.97      0.80      0.88        84

   micro avg       0.99      0.99      0.99      2190
   macro avg       0.98      0.90      0.94      2190
weighted avg       0.99      0.99      0.99      2190

[[2104    2]
 [  17   67]]


In [ ]:
average_precision=average_precision_score(y_test,predicted)
precision,recall,_=precision_recall_curve(y_test,predicted)
plot_pr_curve(recall,precision,average_precision)

In [60]:
model=RandomForestClassifier(class_weight='balanced_subsample',random_state=5)
model.fit(X_train,y_train)
predicted=model.predict(X_test)
probs=model.predict_proba(X_test)
print(roc_auc_score(y_test,probs[:,1]))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))


0.9289021164021165
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2106
           1       0.99      0.79      0.87        84

   micro avg       0.99      0.99      0.99      2190
   macro avg       0.99      0.89      0.93      2190
weighted avg       0.99      0.99      0.99      2190

[[2105    1]
 [  18   66]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [105]:
model=RandomForestClassifier(bootstrap=True,class_weight={0:1,1:12},criterion='gini',
max_depth=10,
min_samples_leaf=10,
n_estimators=20,n_jobs=-1,random_state=5)
model.fit(X_train,y_train)
predicted=model.predict(X_test)
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2106
           1       0.95      0.83      0.89        84

   micro avg       0.99      0.99      0.99      2190
   macro avg       0.97      0.92      0.94      2190
weighted avg       0.99      0.99      0.99      2190

[[2102    4]
 [  14   70]]


In [70]:
param_grid={'n_estimators':[1,30],'max_features':['auto','log2'], 'max_depth': [4, 8],'criterion':['gini','entropy']}
model=RandomForestClassifier(random_state=5)
CV_model=GridSearchCV(estimator=model ,param_grid=param_grid,cv=5,scoring='recall',n_jobs=-1)
CV_model.fit(X_train,y_train)
CV_model.best_params_

{'criterion': 'gini',
 'max_depth': 8,
 'max_features': 'auto',
 'n_estimators': 30}

In [79]:
predicted=CV_model.predict(X_test)
print(roc_auc_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

0.8980972730972732
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2106
           1       0.96      0.80      0.87        84

   micro avg       0.99      0.99      0.99      2190
   macro avg       0.97      0.90      0.93      2190
weighted avg       0.99      0.99      0.99      2190

[[2103    3]
 [  17   67]]


In [96]:
clf1=LogisticRegression(class_weight={0:1,1:15},random_state=5)
clf2=RandomForestClassifier(class_weight={0:1,1:12},criterion='entropy',max_depth=8,max_features='log2',
min_samples_leaf=10,
n_estimators=30,n_jobs=-1,random_state=5)
clf3=DecisionTreeClassifier(random_state=5,class_weight="balanced")
ensemble_model=VotingClassifier(estimators=[('lr',clf1),('rf',clf2),('dt',clf3)],voting='hard')
ensemble_model.fit(X_train, y_train)
ensemble_model.predict(X_test)
print(roc_auc_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8980972730972732
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2106
           1       0.96      0.80      0.87        84

   micro avg       0.99      0.99      0.99      2190
   macro avg       0.97      0.90      0.93      2190
weighted avg       0.99      0.99      0.99      2190

[[2103    3]
 [  17   67]]
